name: Music Together
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check types
      run: |
        pip install mypy types-requests types-cryptography
        mypy . --exclude tests --exclude migrations --exclude examples
    - name: Check coding style
      run: |
        pip install flake8 pep8-naming
        flake8 --exclude venv,migrations --max-line-length=160 --max-complexity=10 --count --statistics
    - name: Setup frontend    
      uses: actions/setup-node@v2
      with:
        node-version: 17.4.0
    - name: npm install and lint    
      run: |
        cd frontend
        npm install
        npm run lint
